spring.application.name: gateway

server:
  port: 8000

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: multiplications
          uri: lb://social-multiplication
          predicates:
            - Path=/api/multiplications/**
          filters:
            - StripPrefix=1
        - id: results
          uri: lb://social-multiplication/results
          predicates:
            - Path=/api/results/**
          filters:
            - StripPrefix=1
        - id: leaders
          uri: lb://gamification/leaders
          predicates:
            - Path=/api/leaders/**
          filters:
            - StripPrefix=1
        - id: stats
          uri: lb://gamification/stats
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1
